kind = "web"
previewPath = "/"
title = "Super Computer"
version = "1.0.0"
id = "artifacts/super-computer"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22001

[services.development]
run = "pnpm --filter @workspace/super-computer run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/super-computer", "run", "build" ]
publicDir = "artifacts/super-computer/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22001"
BASE_PATH = "/"
